name: trabalho_conecta_work
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_floating_bottom_bar: ^1.2.0 # Use underscores em vez de hífens
  searchfield: ^1.1.6
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  parse_server_sdk_flutter: ^8.0.0
  file_picker: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  carousel_slider: ^4.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/imagens/
