name: trabalho_conecta_work
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_floating_bottom_bar: ^1.2.0
  searchfield: ^1.1.6
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.1.2
  parse_server_sdk_flutter: ^8.0.0
  file_picker: ^5.2.3
  google_maps_flutter: ^2.1.1
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  http: ^0.13.6
  permission_handler: ^10.0.0
  url_launcher: ^6.1.10
  flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.0.0
  intl_phone_number_input: ^0.7.0
  intl: ^0.17.0
  dropdown_button2: ^2.3.9
  mime: ^1.0.6
  path: ^1.9.0
  google_place: ^0.4.7
  geopoint: ^1.0.0
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  carousel_slider: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/
